Algorithms README
cbfacademy-solutions/java-course-exercises pull request #13
Opened 2023-09-27 11:48 UTC by sohbaker

- Update Search exercise instructions
- Add test instructions for Sort exercise
- Remove unused links

2023-09-28 16:20 UTC, tanyapowell approved these changes

2023-09-29 11:13 UTC, Genyus requested changes
Suggested adjustment to a couple of heading levels

2023-09-29 11:13 UTC, Genyus commented on exercises/algorithms/README.md
> +## :white_check_mark: Verify Your Implementation
```suggestion
#### :white_check_mark: Verify Your Implementation
```

2023-09-29 11:13 UTC, Genyus commented on exercises/algorithms/README.md
> +## :white_check_mark: Verify Your Implementation
```suggestion
#### :white_check_mark: Verify Your Implementation
```

2023-10-06 01:00 UTC, Genyus approved these changes

2023-10-10 16:42 UTC, merged