Web Applications and HTTP exercise updates
cbfacademy-solutions/java-course-exercises pull request #16
Opened 2023-10-27 22:26 UTC by sohbaker

Introduces the following changes: 
- updates the instructions in the README 
- fixes minor typos
- changes the example URL
- adds sample answers to exercise questions

2023-10-30 17:34 UTC, Genyus requested changes

2023-10-30 17:34 UTC, Genyus commented on exercises/web-applications/login-form.html
Shouldn't this have a basic HTML skeleton rather than being completely empty?

2023-11-06 10:14 UTC, tanyapowell commented
Are these changes part of [TECH-427](https://codingblackfemales.atlassian.net/browse/TECH-427?atlOrigin=eyJpIjoiOGU2NmEwNGZlZGFiNDJhY2FkZTE5YjZmNjdhYTU0YTUiLCJwIjoiaiJ9)?

2023-11-06 11:51 UTC, Genyus commented
@tanyapowell no, this PR isn't related to that ticket

2023-11-14 05:26 UTC, Genyus requested changes
Minor change suggested to HTML boilerplate

2023-11-14 05:26 UTC, Genyus commented on exercises/web-applications/login-form.html
> +    <p>Hello World!</p>
Could make the boilerplate content a little more relevant

```suggestion
    <h1>Login</h1>
    <!-- add content to your login form here -->
```

2023-11-17 13:16 UTC, Genyus approved these changes
LGTM

2023-11-20 17:17 UTC, merged